CREATE TABLE IF NOT EXISTS `Deals` (
  `url` varchar(255) NOT NULL,
  `recrawl` tinyint(1) DEFAULT NULL,
  `use_cookie` tinyint(1) DEFAULT NULL,
  `discovered` datetime DEFAULT NULL,
  `last_inserted` datetime DEFAULT NULL,
  `company_id` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `subtitle` varchar(255) DEFAULT NULL,
  `price` float DEFAULT NULL,
  `value` float DEFAULT NULL,
  `num_purchased` int(11) DEFAULT NULL,
  `text` text,
  `fine_print` text,
  `expired` tinyint(1) DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `expires` datetime DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `address3` varchar(255) DEFAULT NULL,
  `address4` varchar(255) DEFAULT NULL,
  `address5` varchar(255) DEFAULT NULL,
  `address6` varchar(255) DEFAULT NULL,
  `address7` varchar(255) DEFAULT NULL,
  `address8` varchar(255) DEFAULT NULL,
  `address9` varchar(255) DEFAULT NULL,
  `address10` varchar(255) DEFAULT NULL,
  `yelp_rating` float DEFAULT NULL,
  `verified` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`url`)
)